name: 'Continuous Integration'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Google Cloud SDK
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_KEY }}

    - name: Configure Docker for GCP
      run: |
        gcloud auth configure-docker

    - name: Build Docker image
      run: |
        docker build -t gcr.io/latam-mle-project/test-image .
    
    - name: Push Docker image to GCR
      run: |
        docker push gcr.io/latam-mle-project/test-image
